TARGET  := matchengine.exe
INCS =-I/usr/include/mysql -I/usr/include/mysql -I/usr/include/mysql  -I ../network -I ../utils
LIBS =-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -L ../utils -lutils -L ../network -lnetwork -Wl,-Bstatic -lev -ljansson -lmpdec -lrdkafka -lssl -lcrypto -lhiredis -lz -Wl,-Bdynamic -lm -lpthread -ldl -lmysqlclient
include ../makefile.inc
